FROM php:8.3-fpm

RUN apt update && apt install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    msmtp \
    libzip-dev \
    && apt clean && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip

ARG user=laravel_user
ARG uid=1000

RUN echo "sendmail_path = /usr/bin/msmtp -t" > /usr/local/etc/php/conf.d/mail.ini

COPY --from=composer:2.10 /usr/bin/composer /usr/bin/composer

RUN curl -fsSL https://deb.nodesource.com/setup_24.x | bash - \
    && apt install -y nodejs \
    && apt clean && rm -rf /var/lib/apt/lists/*

RUN corepack enable pnpm

ENV PNPM_HOME="/home/${user}/.local/share/pnpm"
ENV PATH="${PATH}:${PNPM_HOME}"

RUN useradd -G www-data,root -u $uid -d /home/$user $user \
    && mkdir -p /home/$user/.composer && chown -R $user:$user /home/$user \
    && mkdir -p /var/www/html && chown -R $user:$user /var/www/html

WORKDIR /var/www/html

EXPOSE 9000
EXPOSE 5173

USER $user